# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5790e848e293eb0bee55401b21bbff92627d8d8ce3af54db2a636a53c240f9e464467a0eaf8c66c89f5643e8fd4df0156444df3972afdfaddefd352011026573

test:
  secret_key_base: 80961fb12febe60af28768777bb7001ec9c5bb756f482429cc9e597905427517c4e7c0cc290ec0086bbb94d91562368337c1dfeef5ffef0612afc744d0ae58f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
